---
title: "Gestion de Portefeuille"
subtitle: "Demo pour vérifier R et LaTeX"
author: Patrick Hénaff
date: "Version: `r format(Sys.Date(), '%d %b %Y')`"
output: pdf_document

header-includes:
  - \usepackage[utf8]{inputenc}
  - \usepackage{graphicx}
  - \usepackage{subfig}
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage{xcolor}
  - \usepackage{amsmath}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r folder-tools, include=TRUE}
get.src.folder <- function() {
  path.expand("../GP/src")
}

get.data.folder <- function() {
  path.expand("../GP/data")
}
```

```{r setup-utils, include=FALSE}
library(lubridate)
source(file.path(get.src.folder(), 'utils.R'))
source(file.path(get.src.folder(), 'FileUtils.R'))
```

# Lecture d'une série

```{r, echo=TRUE}
ts.zc <- get.ts(folder="SBF120", ticker="zc.pa")
```

```{r, fig-1, echo=FALSE, fig.width=10, fig.cap="Zodiac Aerospace"}
plot(ts.zc, main='Zodiac Aerospace')
```